# Generated by Django 5.2 on 2025-05-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('name_section', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id_news', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.CharField(max_length=124)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='noticias/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.section')),
            ],
        ),
    ]
