# Generated by Django 5.2 on 2025-04-14 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_seccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.autor')),
                ('seccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seccion')),
            ],
        ),
    ]
