# Generated by Django 5.2 on 2025-04-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='autor_id',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='seccion_id',
            new_name='seccion',
        ),
    ]
