# Generated by Django 5.2 on 2025-05-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='images_news/'),
        ),
    ]
