# Generated by Django 5.2 on 2025-04-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_autor_id_noticia_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='home/images/'),
            preserve_default=False,
        ),
    ]
