# Generated by Django 5.2 on 2025-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_new_published_alter_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
    ]
