# Generated by Django 5.2 on 2025-04-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticias_aside',
            fields=[
                ('id_aside', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.autor')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='noticias_main',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.autor')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seccion')),
            ],
        ),
        migrations.DeleteModel(
            name='noticia',
        ),
    ]
