# Generated by Django 5.2 on 2025-04-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_noticias_aside_noticias_main_delete_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticias_second',
            fields=[
                ('id_noticia_second', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.autor')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seccion')),
            ],
        ),
    ]
