# Generated by Django 5.2 on 2025-05-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_noticias_second'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='noticias_main',
            new_name='noticias',
        ),
        migrations.RemoveField(
            model_name='noticias_second',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='noticias_second',
            name='seccion',
        ),
        migrations.DeleteModel(
            name='noticias_aside',
        ),
        migrations.DeleteModel(
            name='noticias_second',
        ),
    ]
